name: "Conda Env Check"
description: "Checks conda env files and pin files for outdated packages"
inputs:
  envs:
    description: "A comma-separated list of directories where environment files are stored"
    required: false
    default: "./"
  conda_version:
    description: "The version of conda to use"
    required: false
    default: ""
  lite:
    description: "Whether to use the conda solvers (false) or not (true)"
    required: false
    default: "false"
  fix:
    description: "Whether to fix the environment files or not"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.2.1
        with:
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: '' # optional, default is 

      - name: update-conda
        shell: bash
        run: conda --version

      - name: install-deps
        shell: bash
        run: pip install -r "${{ github.action_path }}/requirements.txt"
      
      - name: find-envs
        id: find-envs
        shell: bash
        env:
          ENVS: ${{ inputs.envs }}
          LITE: ${{ inputs.lite }}
        run: |
          cd ${{ github.action_path }}
          python scripts/check_envs.py $ENVS $LITE /tmp/OUT
          OUTPUT=$(cat /tmp/OUT)

          if [[ $OUTPUT == *"FAIL"* ]]; then
            echo "PERC=failing" >> $GITHUB_OUTPUT
            echo "COLOR=ff0000" >> $GITHUB_OUTPUT
          else
            PERC=$(echo "$OUTPUT" | grep -E '^Percentage:' | awk '{print $2}' | tr -d '%')
            echo "PERC=$PERC%" >> $GITHUB_OUTPUT

            RED=$(printf "%02x" $((255 - $PERC*255/100)))
            GREEN=$(printf "%02x" $(($PERC*255/100)))
            COLOR=$RED$GREEN"00"
            echo "COLOR=$COLOR" >> $GITHUB_OUTPUT
          fi

          echo "$OUTPUT" > $GITHUB_STEP_SUMMARY
          echo "$OUTPUT"
      
      - name: Percentage badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: env_check
          LABEL: 'Conda Env Check'
          STATUS: "${{ steps.find-envs.outputs.perc }}"
          COLOR: ${{ steps.find-envs.outputs.color }}
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Create Pull Request
        if: steps.find-envs.outputs.perc != '100%'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Update environment files'
          committer: CondaEnvChecker <noreply@github.com>
          branch: conda-env-check/patch
          title: 'Update Conda Envs'
          body: ''

      - name: Exit
        shell: bash
        if: steps.find-envs.outputs.perc == 'failing'
        run: exit 1

branding:
  icon: 'check-square'
  color: 'blue'