name: "Conda Env Check"
description: "Checks conda env files and pin files for outdated packages"
inputs:
  envs:
    description: "A comma-separated list of directories where environment files are stored"
    required: false
    default: "./"
  conda_version:
    description: "The version of conda to use"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.2.1
        with:
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: '' # optional, default is 

      - name: install-deps
        shell: bash
        run: pip install pyyaml bs4
      
      - name: find-envs
        shell: bash
        env:
          ENVS: ${{ inputs.envs }}
        run: python "${{ github.action_path }}/scripts/check_envs.py" $ENVS

branding:
  icon: 'check-square'
  color: 'blue'